mav_asif_node:
  ros__parameters:
    mass: 0.70
    gravity: 9.80665
    asif_alpha: 2.0
    backup_controller:
      kp: 10.0
      kv: 3.0
      roll_kp: 10.0
      pitch_kp: 10.0
      yaw_kp: 10.0
      time_horizon: 200
      dt: 0.01
    thrust_model:
      mav_min_thrust: 0.1079 # collective thrust
      mav_max_thrust: 33.9212 # collective thrust

mav_avoidance_control_router:
  ros__parameters:
    mav_id: 1
    mass: 0.70
    gravity: 9.80665
    obstacle_info:
      p_obs: [0.0, 2.1, -1.0, 0.0, -0.1, -1.0]
      r_obs: [0.1, 0.01]
      num_obs: 2
    position_controller:
      kp: 10.0
      kv: 3.0
      roll_kp: 10.0
      pitch_kp: 10.0
      yaw_kp: 10.0
    thrust_model:
      mav_min_thrust: 0.1079 # collective thrust
      mav_max_thrust: 33.9212 # collective thrust